### ISSUE TITLE
[REQUEST] Use known WiFi when phone not connected

### ISSUE THREAD

**Issue by markcs** [karlenek/hasscontrol#11]
If my phone is not connected it would be great if the watch could use the wifi AP that is already configured to access Home Assistant.

My use case is when I go for a run, I do not take my phone. When I return, I would like to be able to open my garage, but currently I can't unless my phone is in bluetooth range. If the watch could connect to my home wifi, then I could trigger this.

Would this be possible?

Thanks for a great app.

**Comment by karlenek** [comment]
Unfortunately that’s not possible. 😕

The only way Garmin let an app communicate with a web api is through a phone. It probably has to do with the battery and memory constraints on the watch.

/Karl

**Comment by hephaestic** [comment]
I know this  issue is closed and this repo hasnt been updated in over a year but hopefully someone can give input on this.

I noticed this garmin music app that syncs podcasts directly via wifi (no bluetooth/phone required after initial setup). 
Would this mean its possible to communicate with HASS some other way without going through the phone?

Unfortunately, that app is not opensource. I've sent an email to the developer and hope to hear back soon. 

App website: https://www.playrun.app/. 
Connect IQ: https://apps.garmin.com/fr/apps/f3f680b0-407b-47a2-bdc5-4ec45f452efe
