### ISSUE TITLE
Bug: "[name] is not a valid group"

### ISSUE THREAD

**Issue by martinkrulltott** [karlenek/hasscontrol#12]
Hey,
I've got a Vivoactive 4 with the app installed and I've managed to log in with a long lived access token.
In groups.yaml I've set up a group called `garmin` like this:

> garmin:
  name: garmin
  entities:
    - light.sovrummet
    - light.kontor_bord

This group works fine in HA and I can use the Service in Developer tools to trigger it on and off.
Under the Group settings in the app I've then entered `garmin`, but when I try to click `Refresh entities: garmin` I get the following response
> **Failed**
   garmin
   is not a valid
   group

Subsequently, when I open the widget start screen it just shows a sad face and `No entities configured`.
Why doesn't this work?

**Comment by karlenek** [comment]
Hi,

Did you write `group.garmin` or `garmin` in settings? 

/Karl

![51121120-604E-4D45-BC7B-8BF2A5150EBB](https://user-images.githubusercontent.com/25322409/106919399-66fb2100-670a-11eb-9d42-1aae5bb3ee3d.jpeg)

**Comment by martinkrulltott** [comment]
Ah, no, I only had `garmin`, using `group.garmin` did the trick, now it works!
Thanks 🙏 
Maybe the docs can be update with some example settings like this, makes it a lot easier to set up 👍
