### ISSUE TITLE
import entities - control scences not possible - certificate/ssl problem ? 

### ISSUE THREAD

**Issue by purche42** [karlenek/hasscontrol#13]
I have problems to read entities from group.
I try to connect to an internal HA system with self signed certificates. I also have CA authority keys imported.
This works well with Chrome without annoying messages.
I'm not sure how IQ handles imported CA on Android.

BTW Login works with Token only. Login with UID/PWD only shows an empty window.

**Comment by karlenek** [comment]
Can you use the official Home Assistant app on your android device?

Can you describe how far you get with a Long-lived Token?
Do you manage to refresh entities from the widget menu or can you interact with some entities?
When you say that login works, do you refer to that the menu in the widget changes and that you can access settings, entities and scenes?

**Comment by purche42** [comment]
i cannot read entities from group.  no interaction with ha . it seems that only Login with Token works. this did not work with uid/pwd

**Comment by pystha** [comment]
Hello,
Long-lived Token works perfectly for me (using https, external url and valid certificate) and I never even tried the widget with user/password).
Added the max number of scenes the Garmin app can handle and I supplementary made a group to import in the widget with some light entities.
Scenes shows up and work without problem but nothing from the group had been important. No error message, nothing.
If I have specified to many scenes, I am not able to import the group?

**Comment by karlenek** [comment]
@pystha, Sorry for being late in reply, is this still a problem?

Did you press refresh entities from the widget menu?

This limit of groups you are talking about, is that because of the text length in ConnectIQ settings? I haven't set any specific limit, the only hard limit would be when the watch runs out of memory. But that should be a really large amount of scenes/entities.

**Comment by pystha** [comment]
The group was never imported unfortunately.
Yes, I was thinking about the text length in ConnectIQ, because I have used all the available characters specifying my scenes so I thought that no room left for the group (something like that).

**Comment by karlenek** [comment]
@pystha, are you still having problems importing a group?
There are some updates in the instructions regarding [group sync](https://github.com/karlenek/hasscontrol#group-sync). Could you please go through it and make sure you have done every step?

Please reopen the issue if you are still having problems.

**Comment by pystha** [comment]
@karlenek I just followed the instructions and everything works great!
I think my problem was that I didn't refreshed the entities on the watch.
Thanks, it's awesome!

**Comment by karlenek** [comment]
Awesome! Thank you @rforro for clarifying the instructions 😊
