### ISSUE TITLE
No entities

### ISSUE THREAD

**Issue by MarkNygaard** [karlenek/hasscontrol#2]
I just installed this widget on a Garmin Vivoactive 4s

If I go to settings and press entities I can see all entities and everything is working fine. However, if I just go into the widget it says no entities. So basically if I want to turn on/off any lights I have to go into widget settings everytime.

Not sure if I did something wrong in the setup or are missing something. I have tried to restart the watch without any changes.

**Comment by MarkNygaard** [comment]
Im an idiot. Found out I needed to change the start screen from scenes to entities in settings.

Thanks for a great app :)

**Comment by karlenek** [comment]
Hi Mark!

Like you say, the default view on startup is to filter for scenes.

I will add some notes about this in the readme!

Let me know if you have any other issues or suggestions 😊

/Karl
