### ISSUE TITLE
Can't login with token

### ISSUE THREAD

**Issue by IroEro** [karlenek/hasscontrol#21]
When trying to trigger a scene with the token configured I get a 403 error on my watch, and my server bans my ip with the error "login attempt or request with invalid authentication".
My server ip is configured using duckdns and a port

**Comment by karlenek** [comment]
Are you sure you are using the correct token with no space before or after the token?

Could you try accessing the home assistant api using an web API tool, Postman or Insomnia for instance? Or calling the api directly from a terminal like the examples here: https://developers.home-assistant.io/docs/api/rest/

```
curl -X GET -H "Authorization: Bearer ABCDEFGH" \
  -H "Content-Type: application/json" https://localhost:8123/api/
 ```
Replace `ABCDEFGH` with your token and `https://localhost:8123` with your url.

**Comment by IroEro** [comment]
Yup, no spaces and correct token.
I just tested with postman and as far as I can tell the response is valid.
I've used the address https://MyDomainName.duckdns.org:MyPort?Content-Type=application/json 
And on authorization i've put a bearer token with my HA token. This is the response I get:

> <!DOCTYPE html>
> <html>
> 
> <head>
>     <link rel="preload" href="/frontend_latest/core.a16e4a28.js" as="script" crossorigin="use-credentials">
>     <link rel="preload" href="/frontend_latest/app.52350e7c.js" as="script" crossorigin="use-credentials">
>     <meta charset="utf-8">
>     <link rel="manifest" href="/manifest.json" crossorigin="use-credentials">
>     <link rel="icon" href="/static/icons/favicon.ico">
>     <meta name="viewport" content="width=device-width,user-scalable=no,viewport-fit=cover">
>     <style>
>         body {
>             font-family: Roboto, sans-serif;
>             -moz-osx-font-smoothing: grayscale;
>             -webkit-font-smoothing: antialiased;
>             font-weight: 400;
>             margin: 0;
>             padding: 0;
>             height: 100%
>         }
>     </style>
>     <title>Home Assistant</title>
>     <link rel="mask-icon" href="/static/icons/mask-icon.svg" color="#03a9f4">
>     <link rel="apple-touch-icon" sizes="180x180" href="/static/icons/favicon-apple-180x180.png">
>     <meta name="apple-itunes-app" content="app-id=1099568401">
>     <meta name="apple-mobile-web-app-capable" content="yes">
>     <meta name="apple-mobile-web-app-status-bar-style" content="default">
>     <meta name="apple-mobile-web-app-title" content="Home Assistant">
>     <meta name="msapplication-square70x70logo" content="/static/icons/tile-win-70x70.png">
>     <meta name="msapplication-square150x150logo" content="/static/icons/tile-win-150x150.png">
>     <meta name="msapplication-wide310x150logo" content="/static/icons/tile-win-310x150.png">
>     <meta name="msapplication-square310x310logo" content="/static/icons/tile-win-310x310.png">
>     <meta name="msapplication-TileColor" content="#03a9f4ff">
>     <meta name="mobile-web-app-capable" content="yes">
>     <meta name="referrer" content="same-origin">
>     <meta name="theme-color" content="#03A9F4">
>     <meta name="color-scheme" content="dark light">
>     <style>
>         #ha-init-skeleton::before {
>             display: block;
>             content: "";
>             height: 56px;
>             background-color: #03A9F4
>         }
> 
>         html {
>             background-color: var(--primary-background-color)
>         }
> 
>         @media (prefers-color-scheme:dark) {
>             html {
>                 background-color: #111
>             }
> 
>             #ha-init-skeleton::before {
>                 background-color: #1c1c1c
>             }
>         }
>     </style>
> </head>
> 
> <body>
>     <div id="ha-init-skeleton"></div>
>     <home-assistant></home-assistant>
>     <script>
>         function _ls(e){var t=document.documentElement,n=t.insertBefore(document.createElement("script"),t.lastChild);return n.defer=!0,n.src=e,n}window.Polymer={lazyRegister:!0,useNativeCSSProperties:!0,dom:"shadow",suppressTemplateNotifications:!0,suppressBindingNotifications:!0},"customElements"in window&&"content"in document.createElement("template")||document.write("<script src='/static/polyfills/webcomponents-bundle.js'><\/script>")
>     </script>
>     <script>
>         function _pf(o,t){var n=document.createElement("link");n.rel="preload",n.as="font",n.type="font/woff2",n.href=o,n.crossOrigin="anonymous",document.head.appendChild(n)}-1===navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("CrOS")&&(_pf("/static/fonts/roboto/Roboto-Regular.woff2"),_pf("/static/fonts/roboto/Roboto-Medium.woff2"))
>     </script>
>     <script crossorigin="use-credentials">
>         import("/frontend_latest/core.a16e4a28.js"),import("/frontend_latest/app.52350e7c.js"),window.customPanelJS="/frontend_latest/custom-panel.2c8f7b73.js",window.latestJS=!0
>     </script>
>     <script></script>
>     <script>
>         window.latestJS||(window.customPanelJS="/frontend_es5/custom-panel.79acc558.js",_ls("/frontend_es5/core.42692e10.js"),_ls("/frontend_es5/app.391b2d03.js"))
>     </script>
>     <script>
>         if (!window.latestJS) {
>         }
>     </script>
> </body>
> 
> </html>

**Comment by karlenek** [comment]
It looks like you are accessing the login page of you Home Assistant. You need to include `/api/` in the url, in order to test the access token. So referring to your example URL above it should be: `https://MyDomainName.duckdns.org:MyPort/api/` the trailing slash is important.

The response should look something like this:
```
{
  "message": "API running."
}
```

Please read more on the link I posted above: https://developers.home-assistant.io/docs/api/rest.

**Comment by IroEro** [comment]
My bad. When using the address with "/api/" the response I get is 401 unauthorized

**Comment by karlenek** [comment]
Alright, try getting it to work with Postman first. The reply should look as my example above. Then try with the same token from the watch. If it still doesn't work, please reopen the issue.

Also, consider using the other login method. You don't have to use a long lived access token.
https://github.com/karlenek/hasscontrol#logging-in

We can continue the discussion, but I will close the issue.

**Comment by IroEro** [comment]
Looks like the api calls specifically were blocked by my either my workplace's ISP or their router (no such issue with webhooks for some reason) . Either way using a VPN fixed it. Thanks for the help and the cool app!
