### ISSUE TITLE
Moving Thru Entities

### ISSUE THREAD

**Issue by titelies** [karlenek/hasscontrol#3]
How does one move thru the various entities that are part of a group?
When I use the Left Center and Left Bottom buttons it moves between widgets and not through the various entities.
Any help would be greatly appreciated. Looking forward to getting this working. Thank you for your work!
Happy Holidays!

**Comment by karlenek** [comment]
What watch are you using?
Also, if you are using a newer watch it sounds like you have glance mode disabled?

**Comment by lvanjaarsveld** [comment]
I have the same issue, basically, it scrolls to the next widget, I do briefly see the scene entity change.

**Comment by karlenek** [comment]
@lvanjaarsveld 
> I have the same issue, basically, it scrolls to the next widget, I do briefly see the scene entity change.

Could you please tell me what watch are you using? And if you have glance mode enabled?

I’m happy to support and help you, however, without more details it will be difficult.

/Karl

**Comment by borky** [comment]
Hi, i have the same issue as the users above, when i want to scroll between the scenes it scrolls to the next widget. 
I have a Fenix 5 Plus watch.

**Comment by karlenek** [comment]
@borky, I cant replicate the issue in my end.
Don't have a real watch, running Garmin simulator.

Could you tell me what watch `Software Version` and `CIQ` you are using?
Menu -> System -> About -> (Software Version is on the first page and CIQ a few pages down).

You are running version 1.1.1 of the app right?

**Comment by borky** [comment]
Yes i am using version 1.1.1 of the app. My Garmin's Software Version is 14.00(e036468) and CIQ 3.2.3

**Comment by karlenek** [comment]
@borky, Im really struggling to run the same version as you in the simulator. Looks like the release of CIQ 3.2.x wasn't released for Fenix 5, but I have also read that this was fixed by Garmin in a later stage and it now looks like Fenix 5 is supported. So it doesn't look like I can run that version in the Garmin simulator and therefore I cant really replicate your issue.

If I throw some debug logging in the code, would you feel comfortable to side load the app and enable logging?

In the meantime I will keep trying to get CIQ 3.2.x running on Fenix 5 in the simulator.

**Comment by karlenek** [comment]
@borky, I have published a new version that I hope will solve your issue. Could you please verify once its available for download. Usually it takes a few hours before the update is visible in the app.

Please reopen the issue if it doesn't fix the bug.

**Comment by borky** [comment]
> @borky, I have published a new version that I hope will solve your issue. Could you please verify once its available for download. Usually it takes a few hours before the update is visible in the app.
> 
> Please reopen the issue if it doesn't fix the bug.

i installed the latest version and now it seems to work. i will further test later today and if i find something i will create a bug.
Thanks a lot for the app and for your fast fix!
