### ISSUE TITLE
Garmin Venu Support?

### ISSUE THREAD

**Issue by patdemko** [karlenek/hasscontrol#4]
Any plans to add support for the Garmin Venu watch?

**Comment by karlenek** [comment]
I have just missed that watch, sure will add it! 

Not sure what Venu you are using.
But since the Venu Sq screen is square, the page indicator wont really fit the screen perfectly.
Will fix that in a future release!

**Comment by karlenek** [comment]
New version that supports Venu watches uploaded to Garmin ConnectIQ.
I think it will take time before it will show up in the app.

Let me know if you run into issues!

**Comment by patdemko** [comment]
Cool!  I''ll give it a try once it's available and let you know.  Thanks!
