### ISSUE TITLE
Scripts are filtered out

### ISSUE THREAD

**Issue by tkupka** [karlenek/hasscontrol#6]
When I have a script in the group it's filtered out and missing in the watch. Switches are loaded perfectly.

**Comment by karlenek** [comment]
@tkupka, that's correct. I filter them out at the moment.
I can add support for scripts this weekend, will post an update once the new version is online 🙂

/Karl

**Comment by karlenek** [comment]
Added support for scripts, will be released together with #7 in release [v1.2.0](/karlenek/hasscontrol/tree/release/v1.2.0)

**Comment by tkupka** [comment]
Great thx a LOT! I really appreciate you app!
