### ISSUE TITLE
Long-lived access token

### ISSUE THREAD

**Issue by tkupka** [karlenek/hasscontrol#7]
When user log in after some time (1-2 hrs) he need to login again. 
Is it possible to use generated Long-lived access token which should fix the problem ?
Token can be generated by a web interface of HA. It would enough to have it as a app config.

**Comment by karlenek** [comment]
@tkupka Yes this is possible, however, you should not have to login again.
What you are describing sounds like a bug in the app or that the app is revoked in Home Assistant.

You can read more about the auth flow used here: [https://developers.home-assistant.io/docs/auth_api/](https://developers.home-assistant.io/docs/auth_api/)

Can you verify that this happens multiple times, ie. try again? And if it keeps happening, can you post some details about your watch and your home assistant instance. watch type, firmware version, Home Assistant version etc.?

Lets try this first, if we cant get it to work I will add Long-lived access token. Had it before so it should be straight forward.

/Karl

**Comment by tkupka** [comment]
I have played around  a bit. Looking to the profile I can see that token is refreshed. It last 30 min and then I'm forced to login again:
```
`Refresh token for https://hasscontrol
Created at 48 minutes ago
Last used at 13 minutes ago from 172.30.33.7`
```

I have separate user for the watch, I have Fenix6S and HA is updated regularly.
`Home Assistant OS 5.10`
`Home Assistant 2021.1.2`
`Fenix FW: 13.10`

**Comment by karlenek** [comment]
@tkupka, Not sure why you have to login again, not able to replicate it.
But I working on support for `long lived access token` like you proposed above.
Should be able to release it within a days or so, will post an update.

**Comment by tkupka** [comment]
That's would be great. I have also no clue why it's asking for login again and again. I tried HA logs and there is nothing.

**Comment by karlenek** [comment]
@tkupka, I have submitted the new version to Garmin. It might take some time before the new version shows in the app and you can download it. Let me know how it goes 🙂

**Comment by tkupka** [comment]
@karlenek It was bit messy in garmin since it was showing me old and new versions depends if I was checking on phone or web browser. Anyway after the installation long living token working perfectly and scripts as well. I already give you review to garmin :-).
Thx a lot for your great job. The app is amazingly useful to me!
